### ISSUE TITLE
Closing context synchronously when closing blocks makes some integration tests hang

### ISSUE THREAD

**Issue by xichen2020** [m3db/m3db#282]
Closing blocks asynchronously causes goroutine number spikes during a topology change because it closes context asynchronously. However after changing it to a blocking close, some integration tests (e.g., TestPeersBootstrapMergePeerBlocks) are stuck.

**Comment by robskillington** [comment]
https://github.com/m3db/m3db/pull/284 attempts to fix this issue.

**Comment by xichen2020** [comment]
The reason why we can't close context synchronously when closing the block is that sometimes we rely on the fact that context is closed asynchronously and close the block before the context closes. As a result, doing a blocking close would lead to a deadlock. #284 attempts to resolve the issue of goroutine explosion by limiting the concurrency of context closing, which has shown to reduce number of goroutines significantly during prod testing.
