### ISSUE TITLE
change map[time.Time]XXX to map[int64]XXX

### ISSUE THREAD

**Issue by cw9** [m3db/m3db#290]
There were cases where we could not find a hit in map for the same time but different timezone, we should use UnixNanoSeconds as the key to represent a time

**Comment by robskillington** [comment]
We need to audit a lot of the code to ensure we are ensuring UTC in <- and UTC out -> and then we can begin to use map[int64]... once we are sure everything comes in as UTC time.

**Comment by richardartoul** [comment]
My profiling over the last three days shows that you'll get a slight performance boost once you do this since the go compiler has a specialized access pattern for map[int64]
