### ISSUE TITLE
Filter by namespace when bootstrapping for commit log bootstrapper namespace

### ISSUE THREAD

**Issue by robskillington** [m3db/m3db#308]
We persist a namespace identifier as we write entries to the commit log, but don't use this whilst bootstrapping from commitlog. The [commitlog bootstrapper](https://github.com/m3db/m3db/blob/master/storage/bootstrap/bootstrapper/commitlog/source.go#L81) needs to filter entries in the commit log based on the namespace it's bootstrapping for.

**Comment by richardartoul** [comment]
@robskillington Is this still an issue? I'm seeing a filter in that code:

```golang
// check if the series belongs to current namespace being bootstrapped
if !namespace.Equal(series.Namespace) {
    continue
}
```

**Comment by prateek** [comment]
As Richie points out, this is already addressed.
