### ISSUE TITLE
Optimise Commit Log Bootstrapping

### ISSUE THREAD

**Issue by prateek** [m3db/m3db#310]
Two changes: 
(1) The commit log bootstrapper reads all the files present in the commit log directory, regardless of the time range it's bootstrapping for. This can be optimised to only read the correct files. 
(2) The commit log bootstrapper is run per namespace, which means we read all commit log files present on disk for each namespace we bootstrap. Optimise this to only require a single read pass across all the namespaces.

**Comment by richardartoul** [comment]
UPDATE:
(1) is complete
(2) is still pending

**Comment by robskillington** [comment]
These are now both complete, closing this out 👍
