### ISSUE TITLE
Investigate long bootstrap times for the commit log bootstrapper

### ISSUE THREAD

**Issue by robskillington** [m3db/m3db#312]
This may be simply a performance issue or could be an edge case with the commit log iterator, but it seems when bootstrapping from multiple large commit log files the commit log bootstrapper takes an exceptionally long time - much longer than previously benchmarked on a single file.

**Comment by richardartoul** [comment]
Investigation revealed that this was simply the result of trying to bootstrap extremely large commitlog files and running into issues with having to msgpack decode and m3tsz encode a large amount of data.
