### ISSUE TITLE
Fix approach to generating mocks

### ISSUE THREAD

**Issue by mmihic** [m3db/m3db#32]
The current approach to generating mocks is untenable as we add developers that aren't the original authors, as it requires manual deduction to trace back from the generated code to the process used to generate that code, esp since there isn't a 1:1 mapping between the generated mocks and the interfaces used to generate them.  We need a simple reproducible build target that can be used to re-generate mocks for the types that require them.

**Comment by robskillington** [comment]
Also require Thrift generated files to be built as part of the same build step.

**Comment by xichen2020** [comment]
This is now fixed. You can pull the latest from master and run `make mock-gen` to generate mocks.

**Comment by robskillington** [comment]
Fixed by #34
