### ISSUE TITLE
Why not Prometheus or Influx

### ISSUE THREAD

**Issue by allyraza** [m3db/m3db#339]
this seems like a big engineering effort you guys are reinventing the wheel instead of using one of the current solution. why not use Prometheus or Influx?

**Comment by pjjw** [comment]
the tl;dr is that prometheus is a single-node system, whereas m3db can handle (some degree of) node failure without issue. influxdb suffers from the same problem unless you pay for their enterprise offering, and at time of this project's origin didn't focus on storage efficiency at all, though this last point has improved somewhat.

**Comment by robskillington** [comment]
Closing this out during issue cleanup.
