### ISSUE TITLE
Make peer bootstrapper incremental flush handle case where fileset files already exist

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3db#511]
Currently, if something goes wrong when trying to read a set of fileset files, that shard/block combination will be marked as unfulfilled, and the peer bootstrapper will try to incrementally flush it.

If the Prepare() method is called for a shard/block combination that already exists, the persist object that is returned will be nil and M3DB will panic during the peer bootstrapping process because it doesn't do the nil check.

We should make the following changes:

1) Re-write the method to return (prepared.Persist, bool, error) instead of just (prepared.Persist, error)
2) Refactor the peer bootstrapper to handle this situation and overwrite the existing files
3) Address other places in the code where this could potentially happen

**Comment by robskillington** [comment]
Agreed with the interface changes, one thing I'm surprised by however is that if a fileset file exists then the fileset bootstrapper will mark that time range as satisified and the peer bootstrapper shouldn't even try to bootstrap that time range.

**Comment by richardartoul** [comment]
@r Discussed via UChat, but in this case it was manifesting because I was testing new code which (unintentionally) was unable to read fileset files generated by older binaries. As a result, the files were on disk but the range was marked as unfulfilled because we couldn't read them.

I think we've had this issue for awhile because its fairly unlikely to happen, we basically have to see real corruption for it to occur.
