### ISSUE TITLE
Make DatabaseBlock.Merge() swap out the underlying context

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3db#580]
Right now, when we call Merge on DatabaseBlock, it will create a new segment which is finalized by the existing context. However, we can't finalize the old segment because there may be some open readers for it so we have to let it sit, and it doesn't get finalized until the block is closed (when the existing context is closed).

What we could do instead is close the old context (which won't finalize the old segment until all outstanding readers are done with it), and then replace the blocks context with a new one which we can call RegisterFinalizer with on the new segment.

This would prevent the old segment from hanging around in memory for as long as it does currently.

**Comment by prateek** [comment]
No longer needed, we removed the underlying contexts in a block
