### ISSUE TITLE
Fix flaky tests introduced by changing shard initial state to "Initializing"

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3db#730]
Updating m3db to use the latest m3cluster which starts all shards in the "initializing" state instead of the "available" state has made some tests flaky.

Known tests:

- [ ] TestEmbeddedConfig
- [ ] TestConfig

**Comment by prateek** [comment]
@richardartoul this still applicable?

**Comment by justinjc** [comment]
#732 fixed this. Closing.
