### ISSUE TITLE
Current documentation seems stale

### ISSUE THREAD

**Issue by huydx** [m3db/m3db#789]
Currently, I'm testing with single node deployment https://m3db.github.io/m3db/how_to/single_node/ 

Some instruction seems wrong. For example namespace/add or placement/init API may need /api/v1 prefix?
But for /writetagged or  /query API, it just returned

```
The requested URL returned error: 500 Internal Server Error
```
without any error log?

Do you have any hint or correct instruction?

**Comment by robskillington** [comment]
Hey @huydx - thanks for noticing.  We are publishing a blog post and readying ourselves for a bit of a wider release, so we definitely had let the changes slip by.  

We'll put together an integration test that makes sure the documented way to setup a single node or a cluster is kept in check.

For now this PR will fix the current issue that you're facing and also allow us to start pushing the latest build as a docker image so you don't get a stale docker image when running through the walkthrough:
https://github.com/m3db/m3db/pull/792

**Comment by robskillington** [comment]
Hey - all documentation should be up to date again @huydx let me know if you see any other/future issues.

**Comment by maozi07** [comment]
The same problems for [https://m3db.github.io/m3/how_to/cluster_hard_way/](https://m3db.github.io/m3/how_to/cluster_hard_way/)
I'm using v0.6.1
For /writetagged, it just returned

```
The requested URL returned error: 500 Internal Server Error
```
